-- Anonymize experts data to remove real names, professional titles, and 
-- regulated terminology (e.g., "변호사", "법률 자문") to comply with the 
-- Attorney Act, Medical Service Act, and similar laws.

UPDATE public.experts
SET 
  name = '법무 정보 가이드 A',
  expertise = '법무 정보 안내',
  career = '군 관련 법무 정보 안내 경력 다년',
  consult_fee = '고객 중심',
  tags = ARRAY['일반 정보','전역 안내','권익 가이드'],
  specialties = ARRAY['군 생활 일반 정보','전역 절차 안내','권익 정보 가이드','관련 자료 안내'],
  description = '군 생활 및 전역 관련 일반 정보를 안내하는 전우찾기 파트너입니다. 직접적인 법률 자문은 제공하지 않습니다.',
  name_en = 'Legal Information Guide A',
  expertise_en = 'Legal Information Guidance',
  career_en = 'Years of experience guiding military-related legal information',
  consult_fee_en = 'Customer Centric',
  description_en = 'A ComradeFind partner providing general information related to military life and discharge. Does not provide direct legal advice.',
  tags_en = ARRAY['General Info','Discharge Guide','Rights Guide'],
  specialties_en = ARRAY['General military info','Discharge process guide','Rights information','Reference materials'],
  name_ja = '法務情報ガイド A',
  expertise_ja = '法務情報案内',
  career_ja = '軍関連の法務情報案内 経験多数',
  consult_fee_ja = '顧客中心',
  description_ja = '軍生活および除隊に関する一般情報を案内する戦友探しパートナーです。直接の法律助言は提供しません。',
  tags_ja = ARRAY['一般情報','除隊案内','権益ガイド'],
  specialties_ja = ARRAY['軍生活一般情報','除隊手続き案内','権益情報ガイド','関連資料案内'],
  name_zh = '法务信息指南 A',
  expertise_zh = '法务信息引导',
  career_zh = '军事相关法务信息引导 多年经验',
  consult_fee_zh = '以客户为中心',
  description_zh = '提供军旅生活及退役相关一般信息的找战友伙伴。不提供直接的法律咨询。',
  tags_zh = ARRAY['一般信息','退役指引','权益指南'],
  specialties_zh = ARRAY['军旅一般信息','退役流程指引','权益信息指南','相关资料介绍']
WHERE id = 'd11c836b-9207-470c-8536-2714b387a19d';

UPDATE public.experts
SET 
  name = '보훈 정보 가이드 B',
  expertise = '보훈·행정 정보 안내',
  career = '보훈·행정 정보 안내 경력 다년',
  consult_fee = '고객 중심',
  tags = ARRAY['혜택 안내','행정 가이드','등록 안내'],
  specialties = ARRAY['보훈 혜택 일반 안내','제대 후 지원 정보','등록 절차 가이드','행정 자료 안내'],
  description = '보훈 및 행정 절차에 관한 일반 정보를 안내하는 전우찾기 파트너입니다.',
  name_en = 'Veterans Information Guide B',
  expertise_en = 'Veterans & Administrative Guidance',
  career_en = 'Years of experience guiding veterans & administrative information',
  consult_fee_en = 'Customer Centric',
  description_en = 'A ComradeFind partner providing general information on veterans benefits and administrative procedures.',
  tags_en = ARRAY['Benefits Info','Admin Guide','Registration Guide'],
  specialties_en = ARRAY['Benefits overview','Post-discharge support info','Registration guide','Administrative materials'],
  name_ja = '援護情報ガイド B',
  expertise_ja = '援護・行政情報案内',
  career_ja = '援護・行政情報案内 経験多数',
  consult_fee_ja = '顧客中心',
  description_ja = '援護および行政手続きに関する一般情報を案内する戦友探しパートナーです。',
  tags_ja = ARRAY['支援案内','行政ガイド','登録案内'],
  specialties_ja = ARRAY['援護制度一般案内','除隊後支援情報','登録手続きガイド','行政資料案内'],
  name_zh = '退伍军人事务指南 B',
  expertise_zh = '退伍军人事务引导',
  career_zh = '退伍军人事务·行政信息引导 多年经验',
  consult_fee_zh = '以客户为中心',
  description_zh = '提供退伍军人福利与行政流程一般信息的找战友伙伴。',
  tags_zh = ARRAY['福利信息','行政指南','登记指引'],
  specialties_zh = ARRAY['退伍福利概览','退役后支持信息','登记流程指南','行政资料介绍']
WHERE id = '54bb1689-b162-4f71-a14b-0e08dc1026d7';

UPDATE public.experts
SET 
  name = '마음 케어 가이드 C',
  expertise = '심리 케어 안내',
  career = '심리 케어 정보 안내 경력 다년',
  consult_fee = '고객 중심',
  tags = ARRAY['심리 케어','적응 가이드','소통 안내'],
  specialties = ARRAY['군 생활 적응 안내','마음 건강 정보','전역 후 적응 가이드','가족 소통 안내'],
  description = '군 생활 적응 및 전역 후 마음 건강 관련 일반 정보를 안내하는 전우찾기 파트너입니다. 진단·치료 행위는 수행하지 않습니다.',
  name_en = 'Wellbeing Guide C',
  expertise_en = 'Mental Care Guidance',
  career_en = 'Years of experience guiding mental care information',
  consult_fee_en = 'Customer Centric',
  description_en = 'A ComradeFind partner providing general information about adjustment and wellbeing. Does not perform diagnosis or treatment.',
  tags_en = ARRAY['Mental Care','Adjustment','Communication'],
  specialties_en = ARRAY['Adjustment guidance','Wellbeing info','Post-discharge adaptation','Family communication'],
  name_ja = 'メンタルケアガイド C',
  expertise_ja = '心理ケア案内',
  career_ja = '心理ケア情報案内 経験多数',
  consult_fee_ja = '顧客中心',
  description_ja = '軍生活適応および除隊後の心の健康に関する一般情報を案内する戦友探しパートナーです。診断・治療は行いません。',
  tags_ja = ARRAY['心理ケア','適応ガイド','コミュニケーション'],
  specialties_ja = ARRAY['軍生活適応案内','心の健康情報','除隊後適応ガイド','家族コミュニケーション'],
  name_zh = '心理关怀指南 C',
  expertise_zh = '心理关怀引导',
  career_zh = '心理关怀信息引导 多年经验',
  consult_fee_zh = '以客户为中心',
  description_zh = '提供军旅适应与退役后心理健康一般信息的找战友伙伴。不进行诊断或治疗。',
  tags_zh = ARRAY['心理关怀','适应指南','沟通指引'],
  specialties_zh = ARRAY['军旅适应指引','心理健康信息','退役后适应指南','家庭沟通指引']
WHERE id = '4450743a-5e3b-4bfc-b7c8-2f8d231e5497';